# Site settings 配置站点
title: 'CopyCat'
description: 'Ctrl+Insert'
keyword: 'Template'
url: 'ragnarokdust.github.io'
baseurl: ''

nav:
  home: '/'
  tags: '/tags.html'

# Footer
footer:
  since: 2019

# Author 
author: 'DAEHYUN KIM'
nickname: 'ragnarokdust'
bio: 'CopyCat'
avatar: '/assets/img/profile.png'

# Search
search: true

# Night mode
nightMode: true

# Comments 
comments:
  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'

# MathJax 
mathjax: true

# Share
social-share: true
social-share-items: ['github']

# theme color 
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'food'

# SNS settings 
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  github: '//github.com/ragnarokdust'

# Tags 
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value
# {{ page.description }}
# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: false

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate]
